### ISSUE TITLE
Improve build time

### ISSUE THREAD

**Issue by 0xalecks** [TempleDAO/temple#410]
- Find out why builds take 10+ minutes
- update Github Actions to use npm caching 
- add .vercelignore files where needed.. ex, subgraph

**Comment by marshall2112** [comment]
Summary of "speed up build" work
- The only real area of improvement is the "dapp build" task, but caching only helps shave off a minute or two (will post a PR shortly)
- Currently vercel handles the yarn install step, so we have no control over that (in terms of caching/speeding up), unless...
- We change our vercel deploy to use "Static" deployments, so we build the artifacts in the GH action (with caching/speed improvements) and then tell vercel to just serve these as-is, saving the install/build steps inside vercel. It gives us more control, but a lot more work to make this change. 
- Also, vercelignore was previously added a few weeks back which probably was the only thing we can control, so that's done. 

Decision: Not worth the effort at this time.
